export const companyNavigationData = [
  {
    id: 1,
    icon: "bx bxs-user-account",
    label: "Company Designation",
    link: "/dashboard/company-designation",
    permission: "View",
    moduleKey: "DESIGNATION",
  },
  {
    id: 2,
    icon: "bx bx-user",
    label: "Company Employee",
    link: "/dashboard/company-employee",
    permission: "View",
    moduleKey: "EMPLOYEE",
  },
  {
    id: 3,
    icon: "bx bxs-calendar-event",
    label: "Important Dates",
    link: "/dashboard/company-important-dates",
    permission: "View",
    moduleKey: "IMPORTANT_DATE",
  },
  {
    id: 4,
    icon: "bx bxs-conversation",
    label: "Meeting List",
    link: "/dashboard/meeting",
    permission: "View",
    moduleKey: "MEETING_LIST",
  },
  {
    id: 5,
    icon: "bx bx-list-ul",
    label: "Company Task List",
    link: "/dashboard/tasks",
    permission: "View",
    moduleKey: "TASK",
  },
  {
    id: 6,
    icon: "bx bxs-buildings",
    label: "Company Project List",
    link: "/dashboard/projects",
    permission: "View",
    moduleKey: "PROJECT_LIST",
  },
  {
    id: 7,
    icon: "bx bx-list-ul",
    label: "Kpi List",
    link: "/dashboard/kpi",
    permission: "View",
    moduleKey: "DATAPOINT_LIST",
  },
  {
    id: 8,
    icon: "bx bx-user",
    label: "Datapoint Table",
    link: "/",
    permission: "View",
    moduleKey: "DATAPOINT_TABLE",
  },
  // {
  //   id: 9,
  //   icon: "bx bxs-business",
  //   label: "Health Score",
  //   link: "/dashboard/healthscore-achieve",
  //   permission: "View",
  //   moduleKey: "HEALTH_SCORE",
  // },
  {
    id: 9,
    icon: "bx bx-user",
    label: "Business Health",
    permission: "View",
    moduleKey: "BUSINESS_HEALTH",
    items: [
      {
        id: 1,
        label: "Health Weightage",
        link: "/dashboard/business/health-weightage",
        permission: "View",
        moduleKey: "HEALTH_WEIGHTAGE",
      },
      {
        id: 2,
        label: "Health Score",
        link: "/dashboard/business/healthscore-achieve",
        permission: "View",
        moduleKey: "HEALTH_SCORE",
      },
      {
        id: 2,
        label: "Company Level Assign",
        link: "/dashboard/business/company-level-assign",
        permission: "View",
        moduleKey: "COMPANY_LEVEL_ASSIGN",
      },
    ],
  },
  {
    id: 10,
    icon: "bx bxs-lock-alt",
    label: "Role & Permission",
    link: "/dashboard/roles/user-permission",
    permission: "View",
    moduleKey: "ROLES_PERMISSION",
  },
  {
    id: 11,
    icon: "bx bxs-lock-alt",
    label: "Brand",
    link: "/dashboard/brand",
    permission: "View",
    moduleKey: "BRAND",
  },
  {
    id: 12,
    icon: "bx bxs-lock-alt",
    label: "Product",
    link: "/dashboard/product",
    permission: "View",
    moduleKey: "PRODUCT",
  },
  {
    id: 15,
    icon: "bx bx-cog",
    label: "Settings",
    link: "/dashboard/calendar",
    permission: "View",
    moduleKey: "ROLES_PERMISSION",
  },
];
