export const companyNavigationData = [
  {
    id: 1,
    icon: "bx bxs-user-account",
    label: "Company Designation",
    link: "/",
    permission: "View",
    moduleKey: "DESIGNATION",
  },
  {
    id: 2,
    icon: "bx bx-user",
    label: "Company Employee",
    link: "/",
    permission: "View",
    moduleKey: "EMPLOYEE",
  },
  {
    id: 3,
    icon: "bx bxs-calendar-event",
    label: "Important Dates",
    link: "/",
    permission: "View",
    moduleKey: "IMPORTANT_DATE",
  },
  {
    id: 4,
    icon: "bx bxs-conversation",
    label: "Meeting List",
    link: "/",
    permission: "View",
    moduleKey: "MEETING_LIST",
  },
  {
    id: 5,
    icon: "bx bx-list-ul",
    label: "Company Task List",
    link: "/",
    permission: "View",
    moduleKey: "TASK",
  },
  {
    id: 6,
    icon: "bx bxs-buildings",
    label: "Company Project List",
    link: "/",
    permission: "View",
    moduleKey: "PROJECT_LIST",
  },
  {
    id: 7,
    icon: "bx bx-list-ul",
    label: "Datapoint List",
    link: "/",
    permission: "View",
    moduleKey: "DATAPOINT_LIST",
  },
  {
    id: 8,
    icon: "bx bx-user",
    label: "Datapoint Table",
    link: "/",
    permission: "View",
    moduleKey: "DATAPOINT_TABLE",
  },
  {
    id: 9,
    icon: "bx bxs-business",
    label: "Business Health",
    permission: "View",
    moduleKey: ["HEALTH_WEIGHTAGE", "HEALTH_SCORE"],
    items: [
      {
        id: 1,
        label: "Health Weightage",
        link: "/",
        permission: "View",
        moduleKey: "HEALTH_WEIGHTAGE",
      },
      {
        id: 2,
        label: "Health Score",
        link: "/",
        permission: "View",
        moduleKey: "HEALTH_SCORE",
      },
    ],
  },
  {
    id: 10,
    icon: "bx bxs-lock-alt",
    label: "Role & Permission",
    link: "/",
    permission: "View",
    moduleKey: "ROLES_PERMISSION",
  },
  {
    id: 15,
    icon: "bx bx-cog",
    label: "Settings",
    link: "/dashboard/calendar",
    permission: "View",
    moduleKey: "ROLES_PERMISSION",
  },
];
