export const kpiMockData = [
  {
    id: 1,
    profileUrl: "user1.png",
    kpi: "Sales Calls",
    goal: 50,
    sum: 45,
    avg: 15,
    period: "Daily",
  },
  {
    id: 2,
    profileUrl: "user2.jpg",
    kpi: "New Leads",
    goal: 100,
    sum: 95,
    avg: 32,
    period: "Weekly",
  },
  {
    id: 3,
    profileUrl: "user1.png",
    kpi: "Closed Deals",
    goal: 20,
    sum: 18,
    avg: 6,
    period: "Monthly",
  },
  {
    id: 4,
    profileUrl: "user4.png",
    kpi: "Customer Visits",
    goal: 40,
    sum: 38,
    avg: 12.7,
    period: "Monthly",
    cells: [
      {
        startDate: "2025-01-01T00:00:00.000Z",
        endDate: "2025-01-30T23:59:59.999Z",
        amount: 5,
      },
      {
        startDate: "2025-03-01T00:00:00.000Z",
        endDate: "2025-03-29T23:59:59.999Z",
        amount: 7,
      },
    ],
  },
  {
    id: 5,
    profileUrl: "user5.jpg",
    kpi: "Support Tickets Resolved",
    goal: 150,
    sum: 142,
    avg: 47.3,
    period: "Monthly",
    cells: [
      {
        startDate: "2025-04-01T00:00:00.000Z",
        endDate: "2025-04-29T23:59:59.999Z",
        amount: 5,
      },
      {
        startDate: "2025-05-01T00:00:00.000Z",
        endDate: "2025-05-30T23:59:59.999Z",
        amount: 5,
      },
      {
        startDate: "2025-06-01T00:00:00.000Z",
        endDate: "2025-06-29T23:59:59.999Z",
        amount: 7,
      },
    ],
  },
  {
    id: 6,
    profileUrl: "user1.png",
    kpi: "Training Sessions",
    goal: 5,
    sum: 4,
    avg: 1.3,
    period: "Quarterly",
  },
  {
    id: 7,
    profileUrl: "user2.jpg",
    kpi: "Bug Fixes",
    goal: 30,
    sum: 28,
    avg: 9.3,
    period: "Weekly",
  },
  {
    id: 8,
    profileUrl: "user1.png",
    kpi: "Code Reviews",
    goal: 60,
    sum: 50,
    avg: 16.6,
    period: "Monthly",
  },
  {
    id: 9,
    profileUrl: "user4.png",
    kpi: "Articles Published",
    goal: 8,
    sum: 6,
    avg: 2,
    period: "Quarterly",
  },
  {
    id: 10,
    profileUrl: "user5.jpg",
    kpi: "Social Media Posts",
    goal: 10,
    sum: 9,
    avg: 3,
    period: "Daily",
  },
  {
    id: 9,
    profileUrl: "user4.png",
    kpi: "Articles Published",
    goal: 8,
    sum: 6,
    avg: 2,
    period: "Quarterly",
  },
  {
    id: 10,
    profileUrl: "user5.jpg",
    kpi: "Social Media Posts",
    goal: 10,
    sum: 9,
    avg: 3,
    period: "Daily",
  },
  {
    id: 9,
    profileUrl: "user4.png",
    kpi: "Articles Published",
    goal: 8,
    sum: 6,
    avg: 2,
    period: "Half-Yearly",
  },
  {
    id: 10,
    profileUrl: "user5.jpg",
    kpi: "Social Media Posts",
    goal: 10,
    sum: 9,
    avg: 3,
    period: "Half-Yearly",
  },
  {
    id: 9,
    profileUrl: "user4.png",
    kpi: "Articles Published",
    goal: 8,
    sum: 6,
    avg: 2,
    period: "Half-Yearly",
  },
  {
    id: 10,
    profileUrl: "user5.jpg",
    kpi: "Social Media Posts",
    goal: 10,
    sum: 9,
    avg: 3,
    period: "Half-Yearly",
  },
  {
    id: 9,
    profileUrl: "user4.png",
    kpi: "Articles Published",
    goal: 8,
    sum: 6,
    avg: 2,
    period: "Yearly",
  },
  {
    id: 10,
    profileUrl: "user5.jpg",
    kpi: "Social Media Posts",
    goal: 10,
    sum: 9,
    avg: 3,
    period: "Yearly",
  },
];
